//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiiTaxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        public int TaxiId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public int Owner { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual People OwnerFK { get; set; }
        public virtual People Other { get; set; }
    }
}
