//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiiTaxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxiPeople
    {
        public Nullable<int> TaxiId { get; set; }
        public Nullable<int> PeopleId { get; set; }
        public int Id { get; set; }
        public string ConfirmCode { get; set; }
        public bool IsConfirmed { get; set; }
        public bool ResourceOnly { get; set; }
    
        public virtual People People { get; set; }
        public virtual Taxi Taxi { get; set; }
    }
}
