//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiiTaxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taxi()
        {
            this.TaxiPeople = new HashSet<TaxiPeople>();
        }
    
        public int TaxiId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public int Owner { get; set; }
        public System.DateTime Time { get; set; }
        public string Confirm { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsOrdered { get; set; }
        public int Approver { get; set; }
    
        public virtual People People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxiPeople> TaxiPeople { get; set; }
        public virtual People People1 { get; set; }
    }
}
